config/routes.rb
Rails.application.routes.draw do
  resources :albums
  devise_for :users
  root to: 'recipes#index'

  get 'search', to: 'recipes#search'

  resources :recipes, only: %i[index show new create edit update]
  resources :recipe_types, only: %i[show new create]
  resources :cuisines, only: %i[ show new create ]

  namespace :api do 
    namespace :v1 do
      resources :recipes, only: %i[show create]
      resources :recipe_types, only: %i[create show]
    end
  end
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, :recipe_type, :cuisine, :difficulty, :cook_time, :difficulty, :ingredients, :cook_method, presence: true

  belongs_to :recipe_type
  belongs_to :cuisine
  belongs_to :user
  has_one_attached :image_recipe

  def cook_time_min
    "#{cook_time} minutos"

  end

end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
    validates :name, presence: {message: 'Você deve preencher o campo TIPO'}
    validates :name, uniqueness: { message: 'Tipo de receita já cadastrado'}
has_many :recipes
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < Api::V1::ApiController
    def show
        @recipe = Recipe.find(params[:id])
        render json: @recipe, status: :ok
    

    rescue ActiveRecord::RecordNotFound
        render json: {message: 'Receita não encontrada'}, status: :not_found
    end

    def create
        @recipe = Recipe.new(params_recipe)
        @recipe.user = current_user
        if @recipe.save
            render json: @recipe, status: :created
        else
            render json: { message: "Falha ao registrar uma receita"}, status: :precondition_failed
        end
    end

private
    def params_recipe
        params.require(:recipe).permit(:title, :image_recipe, :recipe_type_id, :cuisine_id, :cook_time, :difficulty, :ingredients, :cook_method)
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[ new create edit]
  before_action :recipe_type_all, only: %i[ new create edit ] 
  before_action :cuisine_all, only: %i[ new create edit ]
  

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    
    @recipe = Recipe.new(params_recipe)
    @recipe.user = current_user

    if @recipe.save
      redirect_to @recipe
    else
      recipe_type_all
      cuisine_all
      flash.now[:error] = "Você deve informar todos os dados da receita"
      render :new
    end
  end

  def edit
    #if current_user.user_owner?(@recipe)
      @recipe = Recipe.find(params[:id])
    #else
     #redirect_to root_path
    #end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(params_recipe)
      redirect_to @recipe
    else
      recipe_type_all
      flash.now[:error] = "Você deve informar todos os dados da receita"
      render :edit
    end
  end

  def search
    @recipes_search = Recipe.where('title LIKE ?', "%#{params[:search_title]}%")
    if @recipes_search.empty?
      flash[alert] = "Nenhuma receita encontrada"
    else
      flash[alert] = "Resultados de busca:"
    end
  end




private

  def params_recipe
    params.require(:recipe).permit(:title, :image_recipe, :recipe_type_id, :cuisine_id, :difficulty, :cook_time, :difficulty, :ingredients, :cook_method)
  end

  def recipe_type_all
    @recipe_type = RecipeType.all
  end

  def cuisine_all
    @cuisine = Cuisine.all
  end
end

app/views/recipes/_form.html.erb
<div> class="field"
<%= form.label :image_recipe %>
<%= form.file_field :image_recipe %>
</div>

app/views/recipes/edit.html.erb
<h1> <%= "Editar receita" %> </h1>

<%= form_for @recipe do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :image_recipe %>
    <%= f.file_field :image_recipe, multiple: true %>
    <br>
    <%= f.label :recipe_type_id %>
    <%= f.collection_select(:recipe_type_id, @recipe_type, :id, :name) %>
    <br>
    <%= f.label :cuisine_id%>
    <%= f.collection_select(:cuisine_id, Cuisine.all, :id, :cuisine_name) %>
    <br>
    <%= f.label :difficulty %>
    <%= f.text_field :difficulty %>
    <br>
    <%= f.label :cook_time %>
    <%= f.text_field :cook_time %>
    <br>
    <%= f.label :ingredients %>
    <%= f.text_field :ingredients %>
    <br>
    <%= f.label :cook_method %>
    <%= f.text_field :cook_method %>
    <br>
    <%= submit_tag("Enviar", class: "btn btn-dark") %>
    
<% end %>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1><p class="text-center"> CookBook </p></h1>
      <p class="text-center">Bem-vindo ao maior livro de receitas online</p>
    </div>
  </div>
</div>

<%#= link_to 'Enviar uma receita', new_recipe_path %>
<%= link_to 'Registrar Tipo de Receita', new_recipe_type_path %>
<%= link_to 'Registrar Tipo de Cozinha', new_cuisine_path %>

<% @recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe %></h1>
  <%= image_tag(recipe.image_recipe) if recipe.image_recipe.attached?%>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.cuisine_name %></li>
    <li><%=  recipe.difficulty %></li>
    <li><%= recipe.cook_time_min %></li>
  </ul>
<% end %>

app/views/recipes/new.html.erb
<h1> <%= "Enviar receita" %> </h1>
<br>
<br>

<%= form_for @recipe do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :image_recipe %>
    <%= f.file_field :image_recipe, multiple: true %>
    <br>
    <%= f.label :recipe_type_id %>
    <%= f.collection_select(:recipe_type_id, RecipeType.all , :id, :name) %>
    <br>
    <%= f.label :cuisine_id %>
    <%= f.collection_select(:cuisine_id, Cuisine.all, :id, :cuisine_name) %>
    <br>
    <%= f.label :difficulty %>
    <%= f.text_field :difficulty %>
    <br>
    <%= f.label :cook_time %>
    <%= f.text_field :cook_time %>
    <br>
    <%= f.label :ingredients %>
    <%= f.text_field :ingredients %>
    <br>
    <%= f.label :cook_method %>
    <%= f.text_field :cook_method %>
    <br>
    <%= submit_tag("Enviar", class: "btn btn-dark") %>
<% end %>

<br>
<br>

app/views/recipes/search.html.erb
<h1> <%= flash[alert] %> </h1> 

<% @recipes_search.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.cuisine_name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time_min %></li>
  </ul>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<p> 
<%# if @recipe.image_recipe.attached? %>
    <%# @recipe.image_recipe.each do |i| %>
    <%# if @recipe.image_recipe.attached? %>
        <%#= image_tag images%>
    <%# end %>
<%#end%>
</p>
<p><%= image_tag(@recipe.image_recipe) if @recipe.image_recipe.attached?%></p>
<br>
<p><%= t :recipe_send_by %> <%= @recipe.user.email %></p>
<br>

<h3>Detalhes</h3>

<p>Tipo da receita:</p>
<p><%= @recipe.recipe_type.name %></p>
<p>Cozinha</p>
<p><%= @recipe.cuisine.cuisine_name %></p>
<p>Dificuldade</p>
<p><%= @recipe.difficulty %></p>
<p>Tempo de preparo</p>
<p><%= @recipe.cook_time_min %></p>

<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>

<h3>Como Preparar</h3>
<p><%= @recipe.cook_method %></p>

<%= link_to 'Voltar', root_path %>

<% if current_user && current_user == @recipe.user %>
  <%= link_to 'Editar' , edit_recipe_path(@recipe) %>
<%end%>