config/routes.rb
Rails.application.routes.draw do
  resources :albums
  devise_for :users
  root to: 'recipes#index'

  get 'search', to: 'recipes#search'

  resources :recipes, only: %i[index show new create edit update]
  resources :recipe_types, only: %i[show new create]
  resources :cuisines, only: %i[ show new create ]

  namespace :api do 
    namespace :v1 do
      resources :recipes, only: %i[show create]
      resources :recipe_types, only: %i[create show]
    end
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:error] %>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'CookBook', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Inicio', root_path, class: 'nav-link active' %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Enviar uma receita', new_recipe_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Iniciar sessão', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Registrar-se', new_user_registration_path, class: 'nav-link' %>
      </li>
      
      <% end %>
    </ul>
       

      <%= form_tag(search_path, method:  :get, class: "form-inline my-2 my-lg-0") do %>
        <%= label_tag(:search_title) %>
        <%= text_field_tag(:search_title) %>
        <%= submit_tag("Buscar", class: "btn btn-sm btn-outline-secondary") %>
    <% end %>
  </div>
</nav>

<%#= current_user.email %>


<div class="container">
  
  <div class="row">
    <div class="col-2">
    <p>Tipos de Receitas</p>
    <br />
    <p>Tipos de Cozinha</p>
    <br />
    <%# @recipe_types.each do |type| %>
    
    
    </div>
    <div class="col-10">
      
      <%= yield %>
    </div>
  </div>
</div>

<div class="p-3 mb-2 bg-dark text-white">
  <div class="container">
    <div class="row">
      <div class="col">
        <p class="text-center">
        
  CookBook 2019
        </p>
      </div>
    </div>
  </div>
</div>


    <%#= link_to 'Inicio', root_path, class: 'nav-link active' %>
    <%#= link_to 'Minhas Receitas', new_user_session_path %>
    <%#= yield %>
  </body>
</html>